spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  application:
    name: zerobase-login

  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: false
    properties:
      format_sql: true
      hibernate:
        show_sql: true

logging:
  level:
    org.hibernate.SQL: trace
    org.hibernate.type: trace
  file:
    name: ./logs/spring-jpa.log